### PR TITLE
Improved Windows installation instructions

### PR DESCRIPTION
**Pull request by umarbutler**
I modified @freecho's installation instructions for Windows to address the issues I raised in [this](https://github.com/VikParuchuri/marker/pull/54#issuecomment-1938397805) comment on their PR VikParuchuri/marker#54. Credit to @freecho for helping me discover that it was possible to install `marker` on Windows.

### CODE REVIEW

**Review by RGBmaia — APPROVED** [review]
The proposed adaptation works!

**Comment by umarbutler** [comment]
@VikParuchuri Would you care to merge this?

**Comment by Gerkinfeltser** [comment]
Just wanted to say thanks for the update here @umarbutler. Worked perfectly for me here on Win10. 👍

**Review by isee15 — APPROVED** [review]

**Comment by VikParuchuri** [comment]
Thanks for looking into this! The new version has no required system dependencies, so Windows install should be much simpler - https://github.com/VikParuchuri/marker/pull/116

**Pull request closed without merging**
