### PR TITLE
setup instructions for Windows

### PR DESCRIPTION
**Pull request by freecho**
Please check the relevant content in the Windows section of the readme.md.

### CODE REVIEW

**Comment by VikParuchuri** [comment]
Thanks for this!  This doesn't seem to include some dependencies:

- `ocrmypdf`
- `tesseract` + language packs
- ghostscript


Did you find how to install these?

**Comment by 2507544221** [comment]
Thanks,I will continue to study these issues when free time.

**Comment by GdeJoode** [comment]
Hi, I found the tesseract 5 binary on https://github.com/UB-Mannheim/tesseract/wiki. I am just now installing marker and am waiting for a nvidia graphics card to use CUDA. So have not tested it yet.

**Comment by CBIhalsen** [comment]
> 谢谢，我会在空闲时间继续研究这些问题。



> Thanks,I will continue to study these issues when free time.

HI, did you find the perfect solution for Windows?

**Comment by CBIhalsen** [comment]
> Reference in new issue

HI, have you found the perfect solution for windows?

**Comment by freecho** [comment]
I have updated the README.md, and following the steps, both my friend and I have successfully run the project.

**Comment by umarbutler** [comment]
I encountered two issues following the steps detailed in your instructions:
1. I encountered the error `ImportError: failed to find libmagic.  Check your installation` which I resolved by running (in `poetry shell`) `pip install python-magic-bin==0.4.14` as described in [this](https://stackoverflow.com/a/47646141) StackOverflow answer.
2. I encountered the error `AssertionError: Torch not compiled with CUDA enabled` which I resolved by running (in `poetry shell`) `pip uninstall torch` and then `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` (note that this will install `torch` complied for CUDA 11.8) as described by [PyTorch's](https://pytorch.org/get-started/locally/) official documentation.
3. `ModuleNotFoundError: No module named 'pkg_resources'` which I resolved by running `pip install setuptools`.

After running these fixes, I was able to get `marker` working in my Windows environment.

**Comment by umarbutler** [comment]
I have created a new PR that addresses the issues raised in my comment above.

**Comment by VikParuchuri** [comment]
Thanks for looking into this!  The new version has no required system dependencies, so Windows install should be much simpler - https://github.com/VikParuchuri/marker/pull/116

**Pull request closed without merging**
