### PR TITLE
feat: add chinese language setting support

### PR DESCRIPTION
**Pull request by RongkangXiong**

### CODE REVIEW

**Comment by yxhuvud** [comment]
I tried to add swedish in a very similar way, and it didn't work because the spellchecker that is used did not have swedish as a supported language.

**Comment by VikParuchuri** [comment]
I will soon be replacing the spellchecker with something more flexible (a model to detect bad OCR).  This should enable support for many more languages.

**Comment by VikParuchuri** [comment]
For now, I made the spellcheck language optional.  If you omit it, it will not spellchecker.  It may be possible to use other languages that tesseract supports now.

**Comment by VikParuchuri** [comment]
I've added support in master, and disabled spellcheck if the language does not have it.

**Pull request closed without merging**
